version: '3'

services:
  rabbitmq-container:
    image: rabbitmq:3-management-alpine
    restart: always
    hostname: rabbitmq-container
    ports:
      - 5672:5672
      - 15672:15672
  db:
    # -- connect via pod: --
    # mysql -h localhost -u root -p
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: words
      MYSQL_ROOT_PASSWORD: 111111
    volumes:
      - /var/lib/mysql
#  prometheus:
#    image: prom/prometheus:v2.37.9
#    container_name: prometheus
#    ports:
#      - 9090:9090
#    command: "--config.file=/etc/prometheus/prometheus.yaml"
#    volumes:
#      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
#      - ./prometheus:/prometheus
#    restart: unless-stopped
#  grafana:
#    image: grafana/grafana-oss:latest
#    container_name: grafana
#    ports:
#      - 3000:3000
#    volumes:
#      - grafana-data:/var/lib/grafana
#    restart: unless-stopped

  words-api:
    build:
      dockerfile: WordsFactory/Dockerfile
    image: words-api:latest
    restart: always
    ports:
      - 8080
    environment:
      - spring_rabbitmq_host=rabbitmq-container
    depends_on:
      - rabbitmq-container
volumes:
  db:
  grafana-data:

